# Generated by Django 5.1.1 on 2024-10-12 12:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=30, verbose_name='Categoria')),
                ('criado_em', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Noticia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=300, verbose_name='Título')),
                ('subtitulo', models.CharField(max_length=300, verbose_name='Subtítulo')),
                ('criado_em', models.DateField(auto_now_add=True, help_text='yyyy/mm/dd', verbose_name='criado')),
                ('conteudo', models.TextField(default='', verbose_name='Conteudo')),
                ('imagem', models.ImageField(blank=True, upload_to='')),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='app_j24.categoria')),
            ],
            options={
                'db_table': 'noticias',
                'permissions': [('pode_publicar', 'Permissão atribuida à Editores para a publicação da Notícia'), ('autor_noticia', 'Permissão atribuida aos Autores das Notícias.')],
            },
        ),
    ]
