# Generated by Django 5.1.1 on 2024-10-13 13:37

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_j24', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='noticia',
            name='publicada_em',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now, help_text='yyyy/mm/dd', verbose_name='publicada'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='noticia',
            name='publicado',
            field=models.BooleanField(default=False, verbose_name='publicado'),
        ),
    ]
