# Generated by Django 5.1.1 on 2024-10-13 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_j24', '0002_noticia_publicada_em_noticia_publicado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='noticia',
            name='publicado',
        ),
        migrations.AddField(
            model_name='noticia',
            name='publicada',
            field=models.BooleanField(default=False, verbose_name='publicada'),
        ),
        migrations.AlterField(
            model_name='noticia',
            name='publicada_em',
            field=models.DateField(help_text='yyyy/mm/dd', verbose_name='publicada'),
        ),
    ]
