# Generated by Django 5.1.1 on 2024-10-13 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_j24', '0003_remove_noticia_publicado_noticia_publicada_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noticia',
            name='publicada_em',
            field=models.DateField(help_text='yyyy/mm/dd', null=True, verbose_name='publicada'),
        ),
    ]
