# Generated by Django 5.1.1 on 2024-10-13 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_j24', '0004_alter_noticia_publicada_em'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='noticia',
            options={'permissions': [('pode_publicar', 'Permissão atribuida à Editores para a publicação da Notícia'), ('noticia_criar', 'Permissão para criar Notícias.'), ('noticia_alterar', 'Permissão para alterar Notícias.'), ('noticia_excluir', 'Permissão para excluir Notícias.')]},
        ),
    ]
