# Generated by Django 5.1.1 on 2024-11-06 13:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_j24', '0004_comentario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comentario',
            name='noticia',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.RESTRICT, to='app_j24.noticia'),
        ),
    ]
