# Generated by Django 5.1.1 on 2024-10-13 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_j24', '0005_alter_noticia_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noticia',
            name='criado_em',
            field=models.DateTimeField(auto_now_add=True, help_text='dd/mm/yyyy hh:MM', verbose_name='criado'),
        ),
        migrations.AlterField(
            model_name='noticia',
            name='publicada_em',
            field=models.DateTimeField(help_text='dd/mm/yyyy hh:MM', null=True, verbose_name='publicada'),
        ),
    ]
