# Generated by Django 5.1.1 on 2024-10-13 16:10

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_j24', '0006_alter_noticia_criado_em_alter_noticia_publicada_em'),
    ]

    operations = [
        migrations.RenameField(
            model_name='noticia',
            old_name='criado_em',
            new_name='criada_em',
        ),
        migrations.AddField(
            model_name='noticia',
            name='atualizada_em',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, help_text='dd/mm/yyyy hh:MM', verbose_name='atualizada'),
            preserve_default=False,
        ),
    ]
