# Generated by Django 5.1.1 on 2024-10-17 12:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_j24', '0008_alter_noticia_conteudo_alter_noticia_titulo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='noticia',
            name='autor',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='noticia',
            name='publicada_em',
            field=models.DateTimeField(editable=False, help_text='dd/mm/yyyy hh:MM', null=True, verbose_name='Publicada em'),
        ),
    ]
