# Generated by Django 5.1.1 on 2024-10-18 17:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_j24', '0010_remove_noticia_categoria_noticia_categoria'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='noticia',
            options={'permissions': [('pode_publicar', 'Permissão atribuida à Editores para a publicação da Notícia')]},
        ),
    ]
